apiVersion: v2
name: argo-application
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: "https://helm.sh/img/helm.svg"
maintainers:
  - name: DavidConnack
    url: https://github.com/DavidConnack
