nameOverride: ""
fullnameOverride: ""

# This is an array of applications of the app of apps
applications:
  # The ArgoCD project that the app is part of
- project: default
  # The ArgoCD application name
  name: "nginx-one"
  repository:
    url: "https://github.com/bitnami/charts.git"
    branch: "HEAD"
    path: bitnami/nginx
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
